terminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
terminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
terminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
terminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
std::runtime_errorterminate called after throwing an instance of 'std::runtime_error'
  what():  main: N is not divisible by the number of processes.
'
  what():  main: N is not divisible by the number of processes.
